apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: sai-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend-container
          image: anupamraj176/sai-backend:latest

          ports:
            - containerPort: 5001

          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_URL
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CLIENT_URL
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CORS_ORIGINS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_SECRET
            - name: CLOUD_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: API_KEY
            - name: EMAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: EMAIL_USER
            - name: SUPPORT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SUPPORT_EMAIL
            - name: PAYMENT_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PAYMENT_PROVIDER
            - name: RAZORPAY_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: RAZORPAY_KEY_ID
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: NODE_ENV
            - name: PORT
              value: "5001"
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: sai-secret
                  key: API_SECRET
            - name: EMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sai-secret
                  key: EMAIL_APP_PASSWORD
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sai-secret
                  key: GEMINI_API_KEY
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: sai-secret
                  key: RAZORPAY_KEY_SECRET
  
