apiVersion: v1
kind: Secret
metadata:
  name: sai-secret
  namespace: sai-app
type: Opaque
stringData:
  API_SECRET: "YOUR_CLOUDINARY_API_SECRET"
  EMAIL_APP_PASSWORD: "YOUR_GMAIL_APP_PASSWORD"
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
  RAZORPAY_KEY_SECRET: "YOUR_RAZORPAY_KEY_SECRET"
data:
  password: cFVsdWozTVE0eVM4ZzJSbFl0cVZnZWxCNDNVV25HcXREMVpqeWNPeHlSag==
